addons:
  chrome: stable

language: scala
scala:
  - 2.12.10

jdk:
  - openjdk11

before_script:
  # Install Selenium chromedriver
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d selenium-bin
  - export PATH=$PWD/selenium-bin:$PATH

script: sbt -Dfile.encoding=UTF8 g8Test

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.m2
    - $HOME/.coursier/cache
    - $HOME/.cache
    - $HOME/.sbt
